function fullswitches1 = importswitches(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   FULLSWITCHES1 = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   FULLSWITCHES1 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   fullswitches1 = importfile('fullswitches.csv', 1, 14);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/07/17 14:32:17

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Create output variable
fullswitches1 = table;
fullswitches1.VarName1 = cell2mat(raw(:, 1));
fullswitches1.VarName2 = cell2mat(raw(:, 2));
fullswitches1.VarName3 = cell2mat(raw(:, 3));
fullswitches1.VarName4 = cell2mat(raw(:, 4));
fullswitches1.VarName5 = cell2mat(raw(:, 5));
fullswitches1.VarName6 = cell2mat(raw(:, 6));
fullswitches1.VarName7 = cell2mat(raw(:, 7));
fullswitches1.VarName8 = cell2mat(raw(:, 8));
fullswitches1.VarName9 = cell2mat(raw(:, 9));
fullswitches1.VarName10 = cell2mat(raw(:, 10));
fullswitches1.VarName11 = cell2mat(raw(:, 11));
fullswitches1.VarName12 = cell2mat(raw(:, 12));
fullswitches1.VarName13 = cell2mat(raw(:, 13));
fullswitches1.VarName14 = cell2mat(raw(:, 14));
fullswitches1.VarName15 = cell2mat(raw(:, 15));
fullswitches1.VarName16 = cell2mat(raw(:, 16));
fullswitches1.VarName17 = cell2mat(raw(:, 17));
fullswitches1.VarName18 = cell2mat(raw(:, 18));
fullswitches1.VarName19 = cell2mat(raw(:, 19));
fullswitches1.VarName20 = cell2mat(raw(:, 20));

